// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQFB--1rmNH61eEaLvf4qkgOxICvr1dxs',
    appId: '1:779669332173:web:abe3ab8021b21bad1fc984',
    messagingSenderId: '779669332173',
    projectId: 'bubba-days',
    authDomain: 'bubba-days.firebaseapp.com',
    storageBucket: 'bubba-days.appspot.com',
    measurementId: 'G-2VX776CMVY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAdCIduXF8WlXy5xf0I8mM1FdFUb8CqVI',
    appId: '1:779669332173:android:8538f5d2b0aa5c341fc984',
    messagingSenderId: '779669332173',
    projectId: 'bubba-days',
    storageBucket: 'bubba-days.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnu5o1kAaRZQqX_Yip2UY_yrCA2AfzA-4',
    appId: '1:779669332173:ios:f5faf631b7c1c8041fc984',
    messagingSenderId: '779669332173',
    projectId: 'bubba-days',
    storageBucket: 'bubba-days.appspot.com',
    androidClientId: '779669332173-imatlngslsvc1emb1sfhf4phjcnmt6in.apps.googleusercontent.com',
    iosClientId: '779669332173-h6dadbe1f9jc81vj4athr3kl0h0a9ebr.apps.googleusercontent.com',
    iosBundleId: 'com.javier.bubba-days',
  );
}
